#!/usr/bin/env python3
"""Bake repository data files into data_bundle.py for the Cloudflare Worker.

Run once before `wrangler dev` or `wrangler deploy` (wrangler.toml calls this
automatically via its [build] command):

    python3 generate_bundle.py
"""
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
DATA_DIR = REPO_ROOT / "data"
UC_DIR = DATA_DIR / "use-cases"
PKG_DIR = DATA_DIR / "packages"
OUT = Path(__file__).parent / "data_bundle.py"


def load_use_cases() -> list:
    index = json.loads((DATA_DIR / "use-cases.json").read_text())
    results = []
    for uuid in index.get("use_cases", []):
        json_path = UC_DIR / f"{uuid}.json"
        py_path = UC_DIR / f"{uuid}.py"
        if not json_path.exists():
            print(f"  WARNING: missing {json_path}", file=sys.stderr)
            continue
        meta = json.loads(json_path.read_text())
        if meta.get("archived"):
            continue
        meta["source_code"] = py_path.read_text() if py_path.exists() else None
        results.append(meta)
    return results


def load_packages() -> list:
    catalog = json.loads((DATA_DIR / "catalog.json").read_text())
    packages = []

    core = catalog["core"]
    packages.append({
        "id": core["id"],
        "name": core["name"],
        "description": core.get("description", ""),
        "tags": core.get("tags", []),
        "website": core.get("website", ""),
        "docs": core.get("docs", ""),
        "repository": core.get("repository", ""),
    })

    for pkg_id in catalog.get("packages", []):
        p = PKG_DIR / f"{pkg_id}.json"
        if not p.exists():
            print(f"  WARNING: missing {p}", file=sys.stderr)
            continue
        pkg = json.loads(p.read_text())
        if pkg.get("archived"):
            continue
        packages.append({
            "id": pkg["id"],
            "name": pkg["name"],
            "description": pkg.get("description", ""),
            "tags": pkg.get("tags", []),
            "website": pkg.get("website", ""),
            "docs": pkg.get("docs", ""),
            "repository": pkg.get("repository", ""),
        })

    return packages


def main():
    print("Building data_bundle.py...")
    use_cases = load_use_cases()
    packages = load_packages()
    catalog = json.loads((DATA_DIR / "catalog.json").read_text())
    featured_packages = catalog.get("featured_packages", [])
    print(f"  {len(use_cases)} use cases, {len(packages)} packages")

    data = {
        "use_cases": use_cases,
        "packages": packages,
        "featured_packages": featured_packages,
    }
    json_str = json.dumps(data, ensure_ascii=True, separators=(",", ":"))

    out = (
        "# Auto-generated by generate_bundle.py — do not edit.\n"
        "# Run: python3 generate_bundle.py\n"
        "import json as _j\n"
        f"_D = _j.loads({repr(json_str)})\n"
        "USE_CASES = _D['use_cases']\n"
        "PACKAGES = _D['packages']\n"
        "FEATURED_PACKAGES = _D['featured_packages']\n"
    )

    OUT.write_text(out)
    print(f"  Written: {OUT.name} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
